- package-lock.json
- package.json
- src/App.vue
- src/router/index.ts
- src/stores/counter.ts
- src/views/ColorPicker.vue
- tsconfig.json
- yarn.lock
new color picker page. only red.
> npm install + new component

- pull_request_template.md
- Add new template for Pull Requests
> Add Pull Request template

- postcss.config.js
- src/stores/price.ts
- tailwind.config.js
- yarn.lock
- [ x ] Bug fix (non-breaking change which fixes an issue)
This fixes the linter errors introduced by the tailwind merge.
> fix linter error

- src/router/index.ts
- src/stores/price.ts
- src/views/LandingPage.vue
- src/views/TippingPage.vue
Tipping Page implemented (new Vue view and Store actions to manage prices and tipping)
> Tipping page

- src/router/index.ts
- src/stores/price.ts
- src/views/PrintDigital.vue
New Page to choose between e-Paper and Print version
> Digital analog choice

- src/assets/arrows.css
- src/layouts/DefaultLayout.vue
- src/router/index.ts
- src/stores/PaymentStore.ts
- src/views/CustomTip.vue
- src/views/LandingPage.vue
- src/views/PaymentVivawallet.vue
- src/views/TippingPage.vue
New Feature implemented: Custom Tip & Layout Update
> Custom tip

- .env
- src/router/index.ts
implementation to toggle Lite-Mode with an env variable
Lite-Mode: Payment process with only the Landing and the Tipping Page
> Toggle mode

- .dockerignore
- .env
- .env.production
- Dockerfile
- README.md
- docker/entrypoint.sh
- docker/nginx.conf
- src/api/agent.ts
- src/api/endpoints.ts
- src/keycloak/keycloak.ts
Add Docker support to the frontend. This introduces a new `endpoints.ts` in api in order to avoid defining the endpoints as env variables.
> Dockerize the frontend

- src/api/endpoints.ts
removed first '/' from api/endpoints.ts
> fix: fixed '//'

- .env
- .env.production
- docker/entrypoint.sh
- src/router/index.ts
- src/views/AdditionalProducts.vue
- src/views/CustomTip.vue
- src/views/FinalPurchaseConfirmation.vue
- src/views/InformationPrintEpaper.vue
- src/views/LandingPage.vue
- src/views/PaymentConfirmation.vue
- src/views/PaymentVivawallet.vue
- src/views/PrintDigital.vue
- src/views/TippingPage.vue
- src/views/WaitingCountdown.vue
Implementation of a default Layout with templates and slots
> Default layout

- src/layouts/DefaultLayout.vue
- src/router/index.ts
- src/views/CustomTip.vue
- src/views/FinalPurchaseConfirmation.vue
- src/views/InformationPrintEpaper.vue
- src/views/LandingPage.vue
- src/views/PrintDigital.vue
- src/views/TippingPage.vue
Changed Layout to avoid overlap
> Layout fix

- src/views/QRCode.vue
> correct url

- src/views/BackofficeNewVendor.vue
Deleted manual input of url id
> Backoffice views

- README.md
- src/api/api.ts
- src/api/endpoints.ts
- src/stores/vendor.ts
- src/views/BackofficeNewVendor.vue
- src/views/BackofficeUpdateVendor.vue
This adds the possibility to import vendors via csv, but it has no error handling yet.
> Add bulk vendor import

- package.json
- src/api/api.ts
- src/api/endpoints.ts
- src/stores/paymentdata.ts
- src/stores/payout.ts
- src/stores/settings.ts
- src/views/BackofficeAccounting.vue
- src/views/BackofficeCreditPayout.vue
- src/views/BackofficeCredits.vue
- src/views/BackofficeSettings.vue
- src/views/BackofficeUpdateAugustin.vue
- src/views/BackofficeVendorSummary.vue
- yarn.lock
Added the apis for the payments list and the payments/payout, added a calendar filter function, and corrected the settings page.
> Accounting and payments

- src/api/api.ts
- src/keycloak/keycloak.ts
- src/layouts/BackofficeLayout.vue
- src/router/index.ts
- src/stores/items.ts
- src/views/BackofficeNewProduct.vue
- src/views/BackofficeProductSettings.vue
- src/views/BackofficeProductUpdate.vue
- src/views/BackofficeUpdateAugustin.vue
This fixes the update and create product creations.
> fix create+update products

- docker/entrypoint.sh
- src/router/index.ts
- src/stores/vendor.ts
- src/views/HomeView.vue
> Fix env vars and vendor urls

- src/layouts/BackofficeLayout.vue
- src/router/index.ts
This adds the somehow deleted backoffice routes again
> read backoffice routes

- src/views/BackofficeVendorSummary.vue
This changes the qr code from svg to png.
> Download  qr as png

- src/layouts/BackofficeLayout.vue
- src/router/index.ts
- src/stores/keycloak.ts
- src/views/BackofficeVendorSummary.vue
> fix keycloak

- src/stores/paymentdata.ts
- src/views/BackofficeAccounting.vue
- src/views/BackofficeVendorSummary.vue
This shows the payments, but it still needs work in the handler
> fix payments

- src/stores/vendor.ts
- src/views/BackofficeCredits.vue
- src/views/BackofficeVendorSummary.vue
This fixes the search field for vendors in the backoffice
> fix vendor searches

- package.json
- src/layouts/BackofficeLayout.vue
- yarn.lock
This changes the left side menu and makes the behaviour more consistent
> Make a nicer layout for the backoffice sidemenu

- src/layouts/DefaultLayout.vue
- src/views/ParentPaymentProcess.vue
- src/views/VendorOverview.vue
load logo from settings
+ bonus, don't load the layout twice for the shop
> load logo from settings

- src/api/api.ts
- src/views/backoffice/BackofficeCredits.vue
don't log out but login on permission denied and don't fetch vendors, when keycloak isn't ready yet
> don't log out but login on permission denied

- package.json
- src/layouts/DefaultLayout.vue
- src/locales/de.json
- src/locales/en.json
- src/locales/i18n.ts
- src/main.ts
- src/views/CustomTip.vue
- src/views/FailureVivawallet.vue
- src/views/FinalPurchaseConfirmation.vue
- src/views/GoToVendor.vue
- src/views/LandingPage.vue
- src/views/PaymentConfirmation.vue
- src/views/PaymentVivawallet.vue
- src/views/TippingPage.vue
- src/views/WaitingCountdown.vue
- tsconfig.vitest.json
- yarn.lock
Implementation of Translation with i18n
> I18n implementation

- src/stores/vendor.ts
- src/views/backoffice/BackofficeNewVendor.vue
- src/views/backoffice/BackofficeUpdateVendor.vue
- src/views/backoffice/BackofficeUserProfile.vue
- src/views/backoffice/BackofficeVendorSummary.vue
* PhoneNumber is Telephone
* Fetch vendor detail for editing because list vendors is a striped down list of the vendors
> Fetch vendor detail for editing

- .env
- src/locales/de.json
- src/locales/en.json
- src/router/index.ts
- src/views/CustomTip.vue
- src/views/GoToVendor.vue
- src/views/PaymentConfirmation.vue
- src/views/backoffice/BackofficeAccountingPayments.vue
- Changes AGB_URL
- Add space between "Barkasse" and "durch"
- Add space between Tickbox and "Mit Kauf bestätige ich"
- Change wording from Siezen to duzen
- [Add spacing between timestamps in success page](https://github.com/augustin-wien/augustin-frontend/pull/57/commits/d492397d10bb36253fae2888395c983a084990d0)
- [Add method to prevent donation of sum like 0.001 or lower](https://github.com/augustin-wien/augustin-frontend/pull/57/commits/3ef206f77e6b027248fd5727e8359ca4a4cc98bf)
- [Redirect user to go to vendor page if page not found](https://github.com/augustin-wien/augustin-frontend/pull/57/commits/373bf9dc6100e8e4746f0905ab32ada14f4f949f)
> Last fixes before launch

- src/views/FinalPurchaseConfirmation.vue
Add a little margin to the agb checkbox.
> add a little padding

- src/views/backoffice/BackofficeVendorNew.vue
This adds a input validation for the most critical fields and adds better errors.
> Input validation for create vendor

- src/views/TippingPage.vue
> Increase donation suggestions

- src/views/FailureVivawallet.vue
- src/views/backoffice/BackofficeVendorNew.vue
- Removed redirecting user to non-existing route after creating vendor
- Removed "Try again" phrase in failure page since no button to an URL is provided
> Friday fixes

- src/api/api.ts
- src/api/endpoints.ts
- src/layouts/BackofficeLayout.vue
- src/stores/items.ts
- src/views/backoffice/BackofficeAccountingPayments.vue
- src/views/backoffice/BackofficeAccountingPayouts.vue
- src/views/backoffice/BackofficeVendorCreditPayout.vue
Adopt to new items api and add items to the payments overview.
> Adopt items to new api

- src/views/backoffice/BackofficeSettingsUpdate.vue
- enabled update settings function which apparently was not enabled  previously
- upon confirmation, added link back to the settings overview page
> Settings bugfix

- src/api/api.ts
- src/locales/de.json
- Changes sending POST-Request from Multipartform to raw JSON due to Backend acceptance reasons
- Capitalizes create button translation
> Fix create item

- src/locales/de.json
- src/stores/vendor.ts
- src/utils/utils.ts
- src/views/backoffice/BackofficeAccountingPayments.vue
- src/views/backoffice/BackofficeAccountingPayouts.vue
- src/views/backoffice/BackofficeAccountingSales.vue
- src/views/backoffice/BackofficeVendorsCredits.vue
- src/views/backoffice/BackofficeVendorsSummary.vue
This adds a button to each backoffice table to export the data.
Translations are not respected and we have more fields that are hidden in the view, but adoptions should go into a follow up pr.
> feat: make all tables exportable to csv

- src/api/api.ts
Change in accepted data type as requested in order to process images for new items
> changed postitem call to multipart instead of json

- src/views/backoffice/BackofficeAccountingSales.vue
Currently we are missing the "donation" item on the sales page because its behind the backoffice items list filter
> fix: load complete items list on sales page

- src/layouts/BackofficeLayout.vue
> fix: set max header width

- src/views/backoffice/BackofficeAccountingSales.vue
> fix: items name on sales page

- src/components/EmailModal.vue
- src/layouts/BackofficeLayout.vue
- src/layouts/DefaultLayout.vue
- src/layouts/VendorLayout.vue
- src/stores/settings.ts
- src/views/CheckVendorID.vue
- src/views/CustomTip.vue
- src/views/FinalPurchaseConfirmation.vue
- src/views/GoToVendor.vue
- src/views/ItemAvailable.vue
- src/views/LandingPage.vue
- src/views/PaymentConfirmation.vue
- src/views/PaymentVivawallet.vue
- src/views/PrintDigital.vue
- src/views/SelectedItems.vue
- src/views/ShopPage.vue
- src/views/TippingPage.vue
- src/views/VendorOverview.vue
- src/views/VendorViewProfil.vue
- src/views/VendorViewQRCode.vue
- src/views/WaitingCountdown.vue
- src/views/backoffice/BackofficeSettings.vue
- src/views/backoffice/BackofficeSettingsUpdate.vue
builds upon #91 
This avoids to fetch the not yet uploaded image from the backend.
`GET http://localhost:3000/[object%20File] HTTP/1.1" from 172.24.0.1:35606 - 404 19B in 12.232µ`
> Fix logo upload preview

- src/api/api.ts
Don't reinvent the wheel and use the `postForm` from `axios` in updating items
> Use multipart from axios

- src/locales/de.json
- src/locales/en.json
- src/stores/items.ts
- src/views/backoffice/BackofficeProductSettings.vue
- src/views/backoffice/BackofficeProductUpdate.vue
allow to set license settings on items. This is needed for the manual change for a new digital edition of an epaper.
> feat: allow to set license settings on items

- src/views/VendorOverview.vue
- src/views/VendorViewProfil.vue
- src/views/VendorViewQRCode.vue
Fix the vendor page by adding keycloak check and using a watch function.
> fix: vendor page

- src/views/backoffice/MapView.vue
- vite.config.ts
It's not allowed to use unreferenced variables in component calls.
> Fix map fails

- src/stores/vendor.ts
- src/views/backoffice/BackofficeVendorNew.vue
- src/views/backoffice/BackofficeVendorUpdate.vue
Fix redirect after creating a new vendor and correctly indicate if a vendor update failed
> Smal vendor update fixes

- package-lock.json
- package.json
- src/router/index.ts
- src/views/backoffice/BackofficeProductUpdate.vue
- src/views/backoffice/BackofficeSettings.vue
- src/views/backoffice/BackofficeSettingsUpdate.vue
- yarn.lock
Autoreload when Logos are updated
> fix: reloading if pictures are updated

- src/locales/de.json
- src/locales/en.json
- src/stores/ShopStore.ts
- src/stores/payment.ts
- src/views/CustomTip.vue
- src/views/FinalPurchaseConfirmation.vue
- src/views/PaymentVivawallet.vue
- src/views/TippingPage.vue
Refactor the donation store to use only one place of truth.
> fix: refactor donations

- src/models/verificationVivaWallet.ts
- src/views/PaymentConfirmation.vue
This adds a download link for the freshly bought digital newspaper.
> Download on verify

- src/views/backoffice/BackofficeProductUpdate.vue
PDF uploads are broken because we missuesd a label for it
> Fix pdf upload

- src/locales/de.json
- src/locales/en.json
- src/router/index.ts
- src/stores/settings.ts
- src/views/MaintenanceWork.vue
- src/views/backoffice/BackofficeSettingsUpdate.vue
- Adds maintenance view
- Adds settings parameter
> Add maintenance view with specific parameter

- src/locales/de.json
- src/locales/en.json
- src/views/backoffice/BackofficeVendorNew.vue
The order of fields are different in the provided csv and the import script. Also translations are not allowed to have a @ inside see https://github.com/intlify/vue-i18n/issues/118
> fix import vendors from csv

- src/layouts/BackofficeLayout.vue
- src/locales/de.json
- src/locales/en.json
- src/views/backoffice/BackofficeAccountingPayments.vue
- src/views/backoffice/BackofficeAccountingPayouts.vue
- src/views/backoffice/BackofficeAccountingSales.vue
- src/views/backoffice/BackofficeProductSettings.vue
- src/views/backoffice/BackofficeProductUpdate.vue
- src/views/backoffice/BackofficeSettings.vue
- src/views/backoffice/BackofficeVendorCreditPayout.vue
- src/views/backoffice/BackofficeVendorProfile.vue
- src/views/backoffice/BackofficeVendorUpdate.vue
- src/views/backoffice/BackofficeVendorsCredits.vue
- src/views/backoffice/BackofficeVendorsSummary.vue
- src/views/backoffice/MapView.vue
- src/views/backoffice/SettingsUpdate.vue
> Layout unification

- src/components/VendorMapView.vue
- src/views/backoffice/BackofficeVendorUpdate.vue
> fix map addres search

- src/components/WaitingAnimation.vue
- src/layouts/BackofficeLayout.vue
- src/layouts/DefaultLayout.vue
- src/stores/settings.ts
- src/views/CheckVendorID.vue
- src/views/LandingPage.vue
- src/views/PaymentVivawallet.vue
- src/views/ShopPage.vue
- src/views/WaitingCountdown.vue
This improves the loading animation and the language selection. Also it fixes the items when there is no image set.
> More accessability improvements and maintain only one waiting animation

- cypress/e2e/shop/shop.03.buy.cy.ts
- src/api/api.ts
- src/api/endpoints.ts
- src/layouts/DefaultLayout.vue
- src/locales/de.json
- src/locales/en.json
- src/stores/settings.ts
- src/views/backoffice/BackofficeVendorsSummary.vue
- src/views/backoffice/SettingsUpdate.vue
The backoffice is now able to define  customer css for the webshop. An open to do is to give all buttons and sections of the webshop a meaningfull id.
> Allow custom css 

- src/views/backoffice/BackofficeVendorNew.vue
This fixes creating a vendor with non standard  lat/long values.
> fix creating vendor with lat long

- src/utils/utils.ts
Fix lat/lng that are strings in csv import
> fix lat long in csv import

- src/layouts/BackofficeLayout.vue
> Fix  backoffice layout for long emails

- src/views/PaymentConfirmation.vue
> fix payment confirmation page

- src/layouts/DefaultLayout.vue
- src/views/CustomTip.vue
- src/views/ErrorPage.vue
- src/views/FinalPurchaseConfirmation.vue
- src/views/GoToVendor.vue
- src/views/LandingPage.vue
- src/views/PaymentConfirmation.vue
- src/views/ShopPage.vue
- src/views/WaitingCountdown.vue
Use 2 digits for prices, add id's to shop elements, fix overlapping elements.
> 2 digit prices

- .github/dependabot.yml
Let dependabot check for updates
> add: dependabot config

- src/views/ShopPage.vue
Use the 2 digits also in the shop.
> 2 digit prices in shop

- package.json
- src/App.vue
- src/api/api.ts
- src/api/endpoints.ts
- src/components/QrCodeGenerator.vue
- src/layouts/BackofficeLayout.vue
- src/stores/settings.ts
- src/views/backoffice/BackofficeVendorsSummary.vue
- src/views/backoffice/SettingsUpdate.vue
- yarn.lock
This makes it possible to change the favicon and to add a logo to the qr code
> Favicon and qr code improvments

- src/components/QrCodeGenerator.vue
- [] New feature (non-breaking change which adds functionality)
Give the decision to the designer.
> Remove margin from qrcode

- package.json
- yarn.lock
> remove npm run all

- scripts/create-branch.js
- src/components/QrCodeSettings.vue
> add reasonable settings in qr code for the logo in the center

- package.json
This PR updates the version to 0.0.13.
> Update version to 0.0.13

- src/components/QrCodeSettings.vue
- src/views/backoffice/SettingsUpdate.vue
> Qr code improvements

- src/layouts/BackofficeLayout.vue
- src/views/backoffice/BackofficeAccountingPayments.vue
- src/views/backoffice/BackofficeAccountingPayouts.vue
- src/views/backoffice/BackofficeAccountingSales.vue
- src/views/backoffice/BackofficeProductSettings.vue
- src/views/backoffice/BackofficeProductUpdate.vue
- src/views/backoffice/BackofficeVendorCreditPayout.vue
- src/views/backoffice/BackofficeVendorNew.vue
- src/views/backoffice/BackofficeVendorProfile.vue
- src/views/backoffice/BackofficeVendorUpdate.vue
- src/views/backoffice/BackofficeVendorsCredits.vue
- src/views/backoffice/BackofficeVendorsSummary.vue
- src/views/backoffice/MapView.vue
- src/views/backoffice/SettingsUpdate.vue
> use only a global custom-color definition

- src/components/QrCodeSettings.vue
- src/stores/vendor.ts
- src/views/VendorOverview.vue
> fix vendor overview and mass qr code

- .github/workflows/main.yml
- src/components/VendorInfo.vue
- src/utils/utils.ts
- src/views/backoffice/BackofficeVendorProfile.vue
- src/views/backoffice/BackofficeVendorsSummary.vue
> Vendor info as popup

- src/views/backoffice/BackofficeVendorUpdate.vue
> fix: Switched Button

- src/views/ItemAvailable.vue
- src/views/PaymentConfirmation.vue
> feat: add more css classes for custom styling
